# Generated by Django 4.0.4 on 2022-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1data', '0002_alter_circuit_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintresult',
            name='time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
