# Generated by Django 4.0.4 on 2022-05-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1data', '0005_alter_result_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructorstanding',
            name='driver',
        ),
    ]
