# Generated by Django 4.0.4 on 2022-05-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1data', '0009_alter_race_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='driverstanding',
            order_with_respect_to=None,
        ),
    ]
